name: Test build

on:
    push:
        branches:
            - master
            - develop
    schedule:
        - cron: '0 4 * * 0'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@master
        - name: Find latest docker-compose
          run: |
            export DOCKER_COMPOSE_VERSION=$(curl -s https://api.github.com/repos/docker/compose/releases |jq -r '.[]|.name'|grep -v "rc"|head -1)
            echo "Latest docker-compose version is $DOCKER_COMPOSE_VERSION"
            echo ::set-env name=DOCKER_COMPOSE_VERSION::"$DOCKER_COMPOSE_VERSION"
        - name: Install prereqs
          run: |
            echo "test"
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
            sudo apt-get update
            sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
            sudo rm /usr/local/bin/docker-compose
            curl -L https://github.com/docker/compose/releases/download/${{ secrets.DOCKER_COMPOSE_VERSION }}/docker-compose-`uname -s`-`uname -m` > docker-compose
            chmod +x docker-compose
            sudo mv docker-compose /usr/local/bin
        - name: Run docker-compose
          run: |
            docker-compose up -d
        - name: Check the result
          run: |
            RESULT=`docker-compose ps |grep hassio`
            echo "$RESULT"
            if [ -z "$RESULT" ]; then echo "Hassio is not running."; exit 1 ;fi
